---
dependency:
  name: galaxy
driver:
  name: vagrant
lint:
  name: ansible-lint
platforms:
  - name: instance-1
    box: ubuntu/xenial64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
