---
dependency:
  name: galaxy
driver:
  name: vagrant
lint:
  name: yamllint
  options:
    # Override for the line-length linting rule. This is generated due to a
    # formatting error in defaults when the pip_index_url value is piped onto
    # a new line.
    d: {extends: default, rules: {line-length: {max: 120}, braces: {max-spaces-inside: 2}}}
platforms:
  - name: instance
    box: ubuntu/xenial64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
